### ISSUE TITLE
Retry Mechanism

### ISSUE THREAD

**Issue by ispiroglu** [ispiroglu/mercurius#11]
Possible problems for Retry Mechanism

https://xpirr.notion.site/Retry-Mechanism-01b5294f115e49689fb2b81a12e96ef9?pvs=4

**Comment by gurolberkaycinar** [comment]
Scenarios found that may cause errors will be added to issues.

**Comment by gurolberkaycinar** [comment]
- If a message is published and the message cannot be transmitted the first time and goes to the retry queue, the message shouldn't be transmitted to new subscribers and vice versa. A mechanism to check publish and subscribe timestamps to avoid errors should be implemented.
- After a message is published, if the subscriber is not available anymore(graceful or ungraceful) the stray message should be removed.
